### ISSUE TITLE
Can't play video in youtube through webviewx

### ISSUE THREAD

**Issue by Katekko** [adrianflutur/webviewx#22]
When I try I receive this: 
```
Error: URI is missing protocol: about:srcdoc
    at wh (https://www.youtube.com/s/player/2fa3f946/player_ias.vflset/en_US/base.js:422:311)
    at Eh (https://www.youtube.com/s/player/2fa3f946/player_ias.vflset/en_US/base.js:441:42)
    at VK.vv.ww (https://www.youtube.com/s/player/2fa3f946/player_ias.vflset/en_US/base.js:6520:174)
    at VK.ww (https://www.youtube.com/s/player/2fa3f946/player_ias.vflset/en_US/base.js:7204:390)
    at baa.l (https://www.youtube.com/s/player/2fa3f946/player_ias.vflset/en_US/base.js:3025:281)
    at Aa (https://www.youtube.com/s/player/2fa3f946/player_ias.vflset/en_US/base.js:55:40)
    at daa.next (https://www.youtube.com/s/player/2fa3f946/player_ias.vflset/en_US/base.js:56:92)
```

**Comment by adrianflutur** [comment]
Hi, you should be able to play youtube videos by using the `embed` feature of the youtube player, along with `SourceType: URL`.

**Comment by adrianflutur** [comment]
The solution above works just file for `SourceType.url`.
If you want to use the normal youtube page (not /embed/), you can try again now with `SourceType.urlBypass` because there were a number of fixes and new features added, and it might work.
Check them all out here: #26 
Also check out this explaination here #27
Closing this.
